
class Projections():
    COUT_OPERATION = 'cout_operation'
    IS_OFF_MARKET = 'off_market'
    RENDEMENT_BRUT = 'rendement_brut'
    APPORT_BANQUE = 'apport_banque_taux'
    TAUX_INTERET = 'taux_interet'
    NB_ANNEES_EMPRUNT = 'annees_emprunt'
    LOYER_MENSUEL = 'loyer_mensuel'
    LOYER_ANNUEL = 'loyer_annuel_percu'
    ECART_LOYER_MOYEN = 'ecart_au_loyer_moyen'
    CASH_FLOW_ANNUEL = 'cash_flow_annuel'
    CASH_FLOW_ANNUEL_APPORT_TOTAL_INCLU = 'cash_flow_annuel_apport_total_inclu'
    DOIT_PAYER_IMPOT_PREMIERE_ANNEE = 'doit_payer_impot'
    CHARGES_ANNUELLES = 'charges_annuel'
    TAUX_OCCUPATION = 'taux_occupation'
    APPORT_TOTAL = 'apport_total'
    ECART_PRIX_M2_MOYEN_AVANT = 'ecart_prix_m2_prix_moyen_avant'
    ECART_PRIX_M2_MOYEN_APRES = 'ecart_prix_m2_prix_moyen_apres'
    PRIX_M2_AVANT = 'prix_m2_avant'
    PRIX_M2_APRES = 'prix_m2_apres'
    ECART_CHARGES_COPRO_MOYEN = 'ecart_aux_charges_copro_moyen'
    PREMIERE_ANNEE_IMPOSITION = 'first_year_imposition'

class LMNP():
    DEFICIT_RESTANT_AMORTISSEMENT_BIEN = 'deficit_restant_amort_bien'
    DEFICIT_RESTANT_DEPENSES_REELLES = 'deficit_restant_depenses_reelles'
    ANNEES_RESTANTES = 'annees_restants'
    CHARGES_TOTALES = 'charges_totales'
    REVENUS_IMPOSABLES = 'revenus_imposables'
    IS_AMORTISSEMENT_BIEN_REPORTE = 'amort_bien_reporte'
    IS_IMPOSABLE = 'imposable'
    VALEUR_TOTAL_REPORT = 'report'
